/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2019-12-23 16:37:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.club;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_005fclub_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/JUNGEUNA/DOWN/DONGDUK/JAVA/매칭큐/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MatchingQ/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1571677163870L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>동아리 등록 페이지</title>\n");
      out.write("<link rel=stylesheet href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("<script>\n");
      out.write("function userLogout(targetUri) {\n");
      out.write("\tform1.action = targetUri;\n");
      out.write("\tform1.submit();\n");
      out.write("}\n");
      out.write("function myPage(targetUri) {\n");
      out.write("\tform1.action = targetUri;\n");
      out.write("\tform1.submit();\n");
      out.write("}\n");
      out.write("function clubCreate() {\n");
      out.write("\tif (form.club_name.value == \"\") {\n");
      out.write("\t\talert(\"클럽 이름을 입력하십시오.\");\n");
      out.write("\t\tform.club_name.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t} \n");
      out.write("\tif (form.president_code.value == \"\") {\n");
      out.write("\t\talert(\"부장 학번을 입력하십시오.\");\n");
      out.write("\t\tform.president_code.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\t\n");
      out.write("\tif (form.president_phone.value == \"\") {\n");
      out.write("\t\talert(\"부장 연락처를 입력하십시오.\");\n");
      out.write("\t\tform.president_phone.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t} \n");
      out.write("\tif (form.professor_code.value == \"\") {\n");
      out.write("\t\talert(\"교수 코드를 입력하십시오.\");\n");
      out.write("\t\tform.professor_code.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\t\n");
      out.write("\tif (form.professor_phone.value == \"\") {\n");
      out.write("\t\talert(\"교수 연락처를 입력하십시오.\");\n");
      out.write("\t\tform.professor_phone.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t} \n");
      out.write("\tif (form.club_place.value == \"\") {\n");
      out.write("\t\talert(\"모임 장소를 입력하십시오.\");\n");
      out.write("\t\tform.club_place.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\t\n");
      out.write("\tif (form.club_time.value == \"\") {\n");
      out.write("\t\talert(\"모임 시간을 입력하십시오.\");\n");
      out.write("\t\tform.club_time.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t} \n");
      out.write("\tif (form.activity.value == \"\") {\n");
      out.write("\t\talert(\"활동 반경을 체크하십시오.\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif (form.purpose.value == \"\") {\n");
      out.write("\t\talert(\"활동 목적을 체크하십시오.\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif (form.category.value == \"\") {\n");
      out.write("\t\talert(\"카테고리 체크하십시오.\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif (form.description.value == \"\") {\n");
      out.write("\t\talert(\"설명을 입력하십시오.\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tform.submit();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function clubList(targetUri) {\n");
      out.write("\tform.action = targetUri;\n");
      out.write("\tform.submit();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("#search {padding: 20px;}\n");
      out.write("h6 {padding:10px;}\n");
      out.write("li {padding: 8px 16px;}\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("<header class=\"blog-header py-4\">\n");
      out.write("    <div class=\"row flex-nowrap justify-content-between align-items-center\">\n");
      out.write("      <div class=\"col-4 pt-1\"> \n");
      out.write("      \t<p class=\"text-info\">&nbsp;&nbsp;&nbsp;naibulmunyeong</p>      \n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-4 text-center\">\n");
      out.write("        <h4 class=\"blog-header-logo text-dark\">동아리 등록</h4>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-4 d-flex justify-content-end align-items-center\">\n");
      out.write("\t      <nav class=\"my-2 my-md-0 mr-md-3\">\n");
      out.write("\t      \t<form name=\"form1\" method=\"post\" action=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"btn btn-sm btn-outline-secondary\" value=\"로그아웃(&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&nbsp;)\" onClick=\"userLogout('");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("')\">&nbsp;\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"btn btn-sm btn-outline-secondary\" value=\"내정보\" onClick=\"myPage('");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("')\" />\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t  </nav>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("  <div class=\"row\">\n");
      out.write("    <nav class=\"col-md-2 d-none d-md-block bg-light sidebar\">\n");
      out.write("      <div class=\"sidebar-sticky\">\n");
      out.write("        <ul class=\"nav flex-column\">\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link active p-2 text-muted\"  href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("              HOME\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link p-2 text-muted\" href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("            \t수업추천\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link p-2 text-muted\" href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("              \t팀플찾기\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link p-2 text-muted\" href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("              \t동아리 추천\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link p-2 text-muted\" href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("              \t튜터튜티\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("    <main role=\"main\" class=\"col-md-9 ml-sm-auto col-lg-10 px-4\">\n");
      out.write("      <div class=\"d-flex justify-content-between flex-wrap flex-md-nowrap pt-3 pb-2 mb-3\">\n");
      out.write("      \t<div class=\"table-responsive\" id=\"checkbox\">\n");
      out.write("      \t<form name=\"form\" class=\"blog-pagination\" method=\"POST\" action=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("      \t\t<table class=\"table table-shopping\">\n");
      out.write("\t    \t<tr height=\"40\">\n");
      out.write("\t\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">동아리 아이디</td>\n");
      out.write("\t\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" style=\"width: 240\" name=\"club_code\" >\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t  \t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">동아리 이름</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"text\" style=\"width: 240\" name=\"club_name\" >\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t  \t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">부장 학번</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"text\" style=\"width: 240\" name=\"president_code\" >\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\t \n");
      out.write("\t\t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">부장 연락처</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"text\" style=\"width: 240\" name=\"president_phone\" >\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t\t  \t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">교수 코드</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"text\" style=\"width: 240\" name=\"professor_code\" >\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\t \n");
      out.write("\t\t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">교수 연락처</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"text\" style=\"width: 240\" name=\"professor_phone\" >\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t\t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">동아리 장소</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"text\" style=\"width: 240\" name=\"club_place\" >\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t\t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">모임 시간</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"text\" style=\"width: 240\" name=\"club_time\" >\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t\t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">활동 반경</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"activity\" value=\"onCampus\" checked>교내활동\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"activity\" value=\"outCampus\">대외활동\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t\t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">활동 목적</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"purpose\" value=\"hobby\" checked>취미\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"purpose\" value=\"spec\">스펙\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t\t  <tr>\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">분야</td>\n");
      out.write("\t\t\t<td width=\"340\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"category\" value=\"cook\" checked>베이킹, 요리\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"category\" value=\"programing\">프로그래밍\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"category\" value=\"language\">언어, 외국어\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"category\" value=\"culture\">문화, 예술\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"category\" value=\"economy\">경제\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"category\" value=\"health\">생활, 건강\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"category\" value=\"etc\">기타\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t</tr>\t  \n");
      out.write("\t\t  <tr height=\"40\">\n");
      out.write("\t\t\t<td width=\"150\" align=\"center\" bgcolor=\"#f1f1f1\">설명</td>\n");
      out.write("\t\t\t<td width=\"250\" bgcolor=\"ffffff\" style=\"padding-left: 10\">\n");
      out.write("\t\t\t\t<textarea size=\"100\" rows=\"10\" cols=\"50\" name=\"description\"></textarea>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"right\">\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn btn-outline-primary\" value=\"생성\" onClick=\"clubCreate()\"> &nbsp;\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn btn-outline-primary\" value=\"동아리 목록\" onClick=\"clubList('");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write("')\">\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t\t  </table>\n");
      out.write("\t\t  </form>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t </div>\n");
      out.write("\t</main>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /club/register_club.jsp(9,27) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/bootstrap.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /club/register_club.jsp(96,49) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/user/logout");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /club/register_club.jsp(97,122) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/user/logout");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /club/register_club.jsp(98,95) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/user/view");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_eval_c_005furl_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005furl_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005furl_005f3);
        }
        do {
          out.write("\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fparam_005f0(_jspx_th_c_005furl_005f3, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005furl_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005furl_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f0_reused = false;
    try {
      _jspx_th_c_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f3);
      // /club/register_club.jsp(99,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setName("stuId");
      // /club/register_club.jsp(99,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f0 = _jspx_th_c_005fparam_005f0.doStartTag();
      if (_jspx_th_c_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f0);
      _jspx_th_c_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /club/register_club.jsp(111,61) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/review/list ");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /club/register_club.jsp(116,53) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/review/list");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /club/register_club.jsp(121,53) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/teamProject/list");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /club/register_club.jsp(126,53) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/club/list");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /club/register_club.jsp(131,53) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/study/list");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /club/register_club.jsp(141,71) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/club/register");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /club/register_club.jsp(226,90) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/club/list");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }
}
